#Constants
position_dict = {   
      1 : 'Center'
    , 2 : 'Left Wing'
    , 3 : 'Right Wing'
    , 4 : 'Defense'
    , 5 : 'Goalie'
}

team_dict = {
       1: 'Boston Bruins'
    ,  2: 'Buffalo Sabres'
    ,  3: 'Calgary Flames'
    ,  4: 'Chicago Blackhawks'
    ,  5: 'Detroit Red Wings'
    ,  6: 'Edmonton Oilers'
    ,  7: 'Carolina Hurricanes'
    ,  8: 'Los Angeles Kings'
    ,  9: 'Dallas Stars'
    , 10: 'Montréal Canadiens'
    , 11: 'New Jersey Devils'
    , 12: 'New York Islanders'
    , 13: 'New York Rangers'
    , 14: 'Ottawa Senators'
    , 15: 'Philadelphia Flyers'
    , 16: 'Pittsburgh Penguins'
    , 17: 'Colorado Avalanche'
    , 18: 'San Jose Sharks'
    , 19: 'St. Louis Blues'
    , 20: 'Tampa Bay Lightning'
    , 21: 'Toronto Maple Leafs'
    , 22: 'Vancouver Canucks'
    , 23: 'Washington Capitals'
    , 24: 'Arizona Coyotes'
    , 25: 'Anaheim Ducks'
    , 26: 'Florida Panthers'
    , 27: 'Nashville Predators'
    , 28: 'Winnipeg Jets'
    , 29: 'Columbus Blue Jackets'
    , 30: 'Minnesota Wild'
    , 37: 'Vegas Golden Knights'
}
